# Generated by Django 4.1.7 on 2023-03-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perk",
            old_name="explantion",
            new_name="explanation",
        ),
    ]
